//! Generated parent-contract bindings consumed by degenbot Rust code.
//!
//! The files under `rust/crates/contract_bindings` are generated from the
//! parent `contracts/src` Foundry workspace. This facade is the stable import
//! point for the Rust extension and host-side parity tests. Do not add this
//! dependency to Stylus WASM crates; Stylus uses native-test parity against this
//! host-side ABI surface instead.

pub use degenbot_contract_bindings::*;

/// Number of selected parent contract surfaces generated by
/// `just gen-contract-bindings`.
pub const SELECTED_CONTRACT_BINDING_COUNT: usize = 25;

/// Selected parent contract names included in the generated binding crate.
pub const SELECTED_CONTRACT_BINDINGS: &[&str] = &[
    "Executor",
    "AtomicExecutor",
    "LiquidationExecutor",
    "IExecutor",
    "IFlashLoanRouter",
    "IFlashLoanReceiver",
    "IERC3156FlashBorrower",
    "IMorphoFlashLoanCallback",
    "IUniswapV3FlashCallback",
    "IReactorCallback",
    "IUniswapV4Hook",
    "MevPaymasterV9",
    "BaseMevPaymaster",
    "MevSafe",
    "MevBotDelegate",
    "StrategyLedger",
    "PermissionToken",
    "PathFinder",
    "IPathFinder",
    "MultiHopCaller",
    "RouterRegistry",
    "LpTransferLib",
    "TokenStandardIds",
    "TransientStorage",
];
