"""Pinned Uniswap deployment addresses for Arbitrum One."""

from __future__ import annotations

from typing import Final

from degenbot.adapters.addresses import REGISTRY_ADDRESSES as _ADDR

PERMIT2: Final[str] = _ADDR["PERMIT2"]
WETH9: Final[str] = _ADDR["UNIV3_WRAPPED_NATIVE_TOKEN"]
UNIVERSAL_ROUTER: Final[str] = _ADDR["UNIVERSAL_ROUTER_V211"]

V2_FACTORY: Final[str] = _ADDR["UNIV2_FACTORY"]
V2_ROUTER02: Final[str] = _ADDR["UNIV2_ROUTER"]

V3_FACTORY: Final[str] = _ADDR["UNIV3_FACTORY"]
V3_TICK_LENS: Final[str] = "0xbfd8137f7d1516D3ea5cA83523914859ec47F573"
V3_QUOTER_V2: Final[str] = _ADDR["UNIV3_QUOTER_V2"]
V3_SWAP_ROUTER02: Final[str] = _ADDR["UNIV3_SWAP_ROUTER_02"]
V3_NONFUNGIBLE_POSITION_MANAGER: Final[str] = _ADDR["UNIV3_POSITION_MANAGER"]

V4_POOL_MANAGER: Final[str] = _ADDR["UNIV4_POOL_MANAGER"]
V4_QUOTER: Final[str] = _ADDR["UNIV4_QUOTER"]
V4_STATE_VIEW: Final[str] = _ADDR["UNIV4_STATE_VIEW"]
V4_POSITION_MANAGER: Final[str] = _ADDR["UNIV4_POSITION_MANAGER"]
V4_POSITION_DESCRIPTOR: Final[str] = "0xe2023f3fA515Cf070e07fd9d51C1d236E07843F4"

UNISWAPX_DUTCH_V3_REACTOR: Final[str] = _ADDR["UNISWAPX_V3_DUTCH_REACTOR"]
UNISWAPX_ORDER_QUOTER: Final[str] = _ADDR["UNISWAPX_ORDER_QUOTER"]

FACTORIES: Final[frozenset[str]] = frozenset({V2_FACTORY, V3_FACTORY, V4_POOL_MANAGER})
V3_CONTRACTS: Final[frozenset[str]] = frozenset(
    {V3_FACTORY, V3_TICK_LENS, V3_QUOTER_V2, V3_SWAP_ROUTER02, V3_NONFUNGIBLE_POSITION_MANAGER}
)
V4_CONTRACTS: Final[frozenset[str]] = frozenset(
    {V4_POOL_MANAGER, V4_QUOTER, V4_STATE_VIEW, V4_POSITION_MANAGER, V4_POSITION_DESCRIPTOR}
)
UNISWAPX_CONTRACTS: Final[frozenset[str]] = frozenset(
    {UNISWAPX_DUTCH_V3_REACTOR, UNISWAPX_ORDER_QUOTER}
)
