"""Swap venue adapters sourced from the TS registry and DefiLlama references."""

from __future__ import annotations

from degenbot.adapters.addresses import bindings
from degenbot.adapters.templates import (
    AdapterCategory,
    AdapterStatus,
    AdapterTemplate,
    ContractBinding,
    DefiLlamaReference,
    RegistryKey,
)

DL_COMMIT = "5bfdd74e9b98d60e423453406f8e1c8dcc5d8af9"
FLUID_DEFILLAMA_SOURCE = f"DefiLlama/dimension-adapters@{DL_COMMIT}/dexs/fluid-dex/index.ts"
FLUID_DEX_RESERVES_RESOLVER = "0xb8f526718FF58758E256D9aD86bC194a9ff5986D"
FLUID_DEX_RESOLVER = "0x1De42938De444d376eBc298E15D21F409b946E6D"


def dl(path: str, dashboard: str = "dexs", notes: str = "") -> DefiLlamaReference:
    """Create a DefiLlama dimension-adapter reference."""
    return DefiLlamaReference(path=path, dashboard=dashboard, commit=DL_COMMIT, notes=notes)


SWAP_ADAPTERS: tuple[AdapterTemplate, ...] = (
    AdapterTemplate(
        venue="UniswapV2",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.ENABLED,
        contracts=bindings(("UNIV2_FACTORY", "factory"), ("UNIV2_ROUTER", "router")),
        registry_keys=(RegistryKey.FACTORY, RegistryKey.ROUTER),
        execution_module="degenbot.uniswap.v2_liquidity_pool",
        ipc_address_keyed_kinds=("UniswapV2",),
        defillama=(dl("dexs/uniswap-v2.ts"),),
        notes="Degenbot-native V2 pool simulation; TS registry remains the address source.",
    ),
    AdapterTemplate(
        venue="UniswapV3",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.ENABLED,
        contracts=bindings(
            ("UNIV3_FACTORY", "factory"),
            ("UNIV3_SWAP_ROUTER_02", "router"),
            ("UNIV3_QUOTER_V2", "quoter"),
        ),
        registry_keys=(RegistryKey.FACTORY, RegistryKey.ROUTER),
        execution_module="degenbot.uniswap.v3_liquidity_pool",
        ipc_address_keyed_kinds=("UniswapV3",),
        defillama=(dl("dexs/uniswap-v3.ts"),),
        notes="Degenbot-native V3 pool simulation and canonical router/quoter bindings.",
    ),
    AdapterTemplate(
        venue="UniswapV4",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.READ_ONLY,
        contracts=bindings(
            ("UNIV4_POOL_MANAGER", "pool_manager"),
            ("UNIV4_QUOTER", "quoter"),
            ("UNIVERSAL_ROUTER_V20", "router_v20"),
            ("UNIVERSAL_ROUTER_V211", "router_v211"),
        ),
        registry_keys=(RegistryKey.POOL_ID, RegistryKey.ROUTER),
        execution_module="degenbot.uniswap.v4_liquidity_pool",
        ipc_pool_id_required_kinds=("UniswapV4",),
        defillama=(dl("dexs/uniswap-v4.ts"),),
        notes="Pool-id keyed; IPC execution remains disabled until pool-id-aware wire support lands.",
    ),
    AdapterTemplate(
        venue="UniswapX",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.READ_ONLY,
        contracts=bindings(
            ("UNISWAPX_V3_DUTCH_REACTOR", "reactor"),
            ("UNISWAPX_ORDER_QUOTER", "order_quoter"),
            ("PERMIT2", "permit2"),
        ),
        registry_keys=(RegistryKey.ADDRESS,),
        quote_module="coordinator.src.uniswapx",
        ipc_recognized_kinds=("UniswapUniversalRouter",),
        notes="Intent source and quote validation; not a pool-simulation adapter.",
    ),
    AdapterTemplate(
        venue="AggregatorV6",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.ENABLED,
        contracts=bindings(
            ("ONEINCH_AGG_V6", "1inch"),
            ("ZEROX_EXCHANGE_PROXY", "0x"),
            ("PARASWAP_AUGUSTUS_V6", "paraswap"),
            ("ODOS_ROUTER_V2", "odos"),
            ("KYBER_META_AGGREGATION_V2", "kyber"),
            ("OPENOCEAN_EXCHANGE", "openocean"),
        ),
        registry_keys=(RegistryKey.ROUTER,),
        quote_module="degenbot.execution_adapters.aggregator_validator",
        ipc_recognized_kinds=(
            "AggregatorV6",
            "OneInchV6",
            "ZeroX",
            "ParaSwap",
            "Odos",
            "KyberSwap",
            "OpenOcean",
        ),
        defillama=(
            dl("aggregators/1inch-agg/index.ts", "aggregators"),
            dl("aggregators/paraswap/index.ts", "aggregators"),
            dl("aggregators/odos/index.ts", "aggregators"),
            dl("aggregators/kyberswap/index.ts", "aggregators"),
            dl("aggregators/openocean/index.ts", "aggregators"),
        ),
        notes="On-chain Executor permits only the six ADR-016 routers in this binding.",
    ),
    AdapterTemplate(
        venue="SushiSwap",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.ENABLED,
        contracts=bindings(
            ("SUSHI_V2_FACTORY", "v2_factory"),
            ("SUSHI_V2_ROUTER", "v2_router"),
            ("SUSHI_V3_FACTORY", "v3_factory"),
            ("SUSHI_V3_SWAP_ROUTER", "v3_router"),
        ),
        registry_keys=(RegistryKey.FACTORY, RegistryKey.ROUTER),
        execution_module="degenbot.sushiswap.pools",
        ipc_address_keyed_kinds=("SushiSwapV2", "SushiSwapV3"),
        defillama=(
            dl("dexs/sushiswap-v3.ts"),
            dl("aggregators/sushiswap-agg.ts", "aggregators"),
        ),
        notes="Degenbot-native V2/V3 fork classes.",
    ),
    AdapterTemplate(
        venue="PancakeSwapV3",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.ENABLED,
        contracts=bindings(
            ("PANCAKE_V3_SMART_ROUTER", "smart_router"),
            ("PANCAKE_V3_QUOTER_V2", "quoter_v2"),
        ),
        registry_keys=(RegistryKey.ROUTER,),
        execution_module="degenbot.pancakeswap.pools",
        ipc_address_keyed_kinds=("PancakeSwapV2", "PancakeSwapV3"),
        defillama=(dl("dexs/pancakeswap-v3.ts"),),
        notes="Degenbot-native Pancake V3 pool class with dedicated Arbitrum router bindings.",
    ),
    AdapterTemplate(
        venue="Camelot",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.ENABLED,
        contracts=bindings(
            ("CAMELOT_V2_FACTORY", "v2_factory"),
            ("CAMELOT_V2_ROUTER", "v2_router"),
            ("CAMELOT_V3_SWAP_ROUTER", "algebra_v3_router"),
            ("CAMELOT_ALGEBRA_V4_SWAP_ROUTER", "algebra_v4_router"),
            ("ALGEBRA_V4_FACTORY", "algebra_v4_factory"),
        ),
        registry_keys=(RegistryKey.FACTORY, RegistryKey.ROUTER),
        execution_module="degenbot.execution_adapters.camelot_v3_adapter",
        ipc_address_keyed_kinds=("CamelotV2", "CamelotV3"),
        ipc_recognized_kinds=("CamelotAlgebraV4", "Algebra"),
        defillama=(dl("dexs/camelot-v3/index.ts"),),
        notes="Camelot V2 is degenbot-native; Camelot V3 uses the project Algebra adapter.",
    ),
    AdapterTemplate(
        venue="FraxSwap",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.REFERENCE_ONLY,
        contracts=bindings(("FRAXSWAP_FACTORY", "factory")),
        registry_keys=(RegistryKey.FACTORY,),
        ipc_recognized_kinds=("FraxSwap",),
        defillama=(dl("dexs/frax-swap/index.ts"),),
        notes="V2-style source; no production execution path is enabled from Python yet.",
    ),
    AdapterTemplate(
        venue="Aerodrome",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.REFERENCE_ONLY,
        contracts=(),
        registry_keys=(RegistryKey.ADDRESS,),
        execution_module="degenbot.aerodrome.pools",
        ipc_address_keyed_kinds=("Aerodrome",),
        notes="Degenbot-native on Base; Arbitrum routing remains rejected by TS encoder.",
    ),
    AdapterTemplate(
        venue="Curve",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.ENABLED,
        contracts=bindings(("CURVE_ROUTER", "router"), ("CURVE_STABLESWAP_REGISTRY", "registry")),
        registry_keys=(RegistryKey.ADDRESS,),
        execution_module="degenbot.curve.curve_stableswap_liquidity_pool",
        ipc_address_keyed_kinds=("Curve",),
        defillama=(dl("dexs/curve/index.ts"),),
        notes="Legacy Curve is degenbot-native; CurveNG is handled by the project adapter.",
    ),
    AdapterTemplate(
        venue="CurveNG",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.ENABLED,
        contracts=bindings(("CURVE_ROUTER", "router"), ("CURVE_STABLESWAP_REGISTRY", "registry")),
        registry_keys=(RegistryKey.ADDRESS,),
        execution_module="degenbot.execution_adapters.curve_ng_adapter",
        ipc_address_keyed_kinds=("CurveNG",),
        defillama=(dl("dexs/curve/index.ts"),),
        notes="Project adapter wraps NG uint256-index pool math and degenbot registry integration.",
    ),
    AdapterTemplate(
        venue="Balancer",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.ENABLED,
        contracts=bindings(
            ("BALANCER_V2_VAULT", "v2_vault"),
            ("BALANCER_V3_VAULT", "v3_vault"),
            ("BALANCER_V3_ROUTER", "v3_router"),
            ("BALANCER_V3_BATCH_ROUTER", "v3_batch_router"),
            ("BALANCER_V3_AGGREGATOR_ROUTER", "v3_aggregator_router"),
        ),
        registry_keys=(RegistryKey.VAULT, RegistryKey.ROUTER),
        execution_module="degenbot.execution_adapters.balancer_v3_adapter",
        ipc_address_keyed_kinds=("BalancerV2",),
        ipc_recognized_kinds=("BalancerV3",),
        defillama=(dl("dexs/balancer-v3/index.ts"),),
        notes=(
            "V2/V3 vault architecture; executable only as coordinator-validated pre-encoded calldata "
            "with Executor post-call balance-delta checks."
        ),
    ),
    AdapterTemplate(
        venue="DodoPmm",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.ENABLED,
        contracts=bindings(("DODO_V2_PROXY02", "proxy02")),
        registry_keys=(RegistryKey.ADDRESS, RegistryKey.ROUTER),
        execution_module="degenbot.execution_adapters.dodo_pmm_adapter",
        ipc_address_keyed_kinds=("DodoPmm",),
        defillama=(dl("dexs/dodo/index.ts"), dl("aggregators/dodo-agg/index.ts", "aggregators")),
        notes="Project PMM pool adapter is live; router binding is for monitor and path metadata.",
    ),
    AdapterTemplate(
        venue="MaverickV2",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.REFERENCE_ONLY,
        contracts=bindings(
            ("MAVERICK_V2_ROUTER", "router"),
            ("MAVERICK_V2_QUOTER", "quoter"),
            ("MAVERICK_V2_REWARD_ROUTER", "reward_router"),
        ),
        registry_keys=(RegistryKey.ROUTER,),
        execution_module="degenbot.execution_adapters.maverick_v2_adapter",
        ipc_recognized_kinds=("MaverickV2",),
        defillama=(dl("dexs/maverick-v2/index.ts"),),
        notes="Venue metadata is sourced; executable bin-shift simulation remains disabled.",
    ),
    AdapterTemplate(
        venue="FluidDex",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.REFERENCE_ONLY,
        contracts=(
            ContractBinding(
                export_name="DEX_RESERVES_RESOLVER",
                address=FLUID_DEX_RESERVES_RESOLVER,
                role="defillama_reserves_resolver",
                source_file=FLUID_DEFILLAMA_SOURCE,
            ),
            ContractBinding(
                export_name="DEX_RESOLVER",
                address=FLUID_DEX_RESOLVER,
                role="defillama_pool_config_resolver",
                source_file=FLUID_DEFILLAMA_SOURCE,
            ),
        ),
        registry_keys=(RegistryKey.EXTERNAL_API,),
        execution_module="degenbot.execution_adapters.fluid_dex_adapter",
        ipc_recognized_kinds=("FluidDex",),
        defillama=(dl("dexs/fluid-dex/index.ts"), dl("dexs/fluid-dex-lite/index.ts")),
        notes=(
            "DefiLlama resolver addresses are pinned for pool discovery; TS registry has no "
            "canonical Fluid execution binding yet."
        ),
    ),
    AdapterTemplate(
        venue="Solidly",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.ENABLED,
        contracts=bindings(
            ("RAMSES_ROUTER_V2", "ramses_router"), ("RAMSES_UNIVERSAL_ROUTER", "ramses_ur")
        ),
        registry_keys=(RegistryKey.ROUTER,),
        execution_module="degenbot.execution_adapters.solidly_adapter",
        ipc_address_keyed_kinds=("Solidly",),
        ipc_recognized_kinds=("RamsesV2",),
        defillama=(
            dl("dexs/ramsesx-arb-legacy.ts"),
            dl("dexs/ramsesx-arb-cl.ts"),
            dl("dexs/solidly-v3/index.ts"),
        ),
        notes="Project Solidly adapter covers Ramses/Chronos/Solidlizard-style pools.",
    ),
    AdapterTemplate(
        venue="RegistryPocDexLanes",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.REFERENCE_ONLY,
        contracts=bindings(
            ("LFJ_LB_ROUTER_V21", "lfj_router_v21"),
            ("LFJ_LB_ROUTER_V22", "lfj_router_v22"),
            ("KYBER_ELASTIC_ROUTER", "kyber_elastic_router"),
            ("KYBER_ELASTIC_FACTORY", "kyber_elastic_factory"),
            ("GMX_V2_EXCHANGE_ROUTER", "gmx_exchange_router"),
            ("WOMBAT_ROUTER", "wombat_router"),
        ),
        registry_keys=(RegistryKey.ROUTER,),
        ipc_recognized_kinds=("KyberElastic", "LFJLiquidityBook", "GMXV2", "Wombat"),
        defillama=(
            dl("aggregators/joe-agg/index.ts", "aggregators"),
            dl("aggregators/kyberswap/index.ts", "aggregators"),
            dl("dexs/gmx-v2-gmx-v2-swap.ts"),
            dl("dexs/wombat-exchange/index.ts"),
        ),
        notes=(
            "Registry POC lanes require strategy-owned calldata synthesis before production routing; "
            "DefiLlama references pin the venue families for discovery and volume context."
        ),
    ),
    AdapterTemplate(
        venue="RFQAndCrossChainAggregators",
        category=AdapterCategory.SWAP,
        status=AdapterStatus.REFERENCE_ONLY,
        contracts=bindings(
            ("BEBOP_SETTLEMENT", "bebop"),
            ("HASHFLOW_ROUTER", "hashflow"),
            ("WOOFI_ROUTER_V2", "woofi_v2"),
            ("WOOFI_ROUTER_ALT", "woofi_alt"),
            ("OKX_DEX_ROUTER", "okx"),
            ("ENSO_ROUTER", "enso"),
            ("SQUID_ROUTER", "squid"),
            ("LIFI_DIAMOND", "lifi"),
            ("RANGO_DIAMOND", "rango"),
            ("RUBIC_PROXY_V3", "rubic"),
            ("NATIVE_ROUTER_V4", "native_v4"),
            ("NATIVE_ROUTER_V3", "native_v3"),
        ),
        registry_keys=(RegistryKey.ROUTER,),
        ipc_recognized_kinds=(
            "Bebop",
            "Hashflow",
            "WooFi",
            "OKXDex",
            "Enso",
            "Squid",
            "LiFi",
            "Rango",
            "Rubic",
            "Native",
        ),
        defillama=(
            dl("aggregators/bebop/index.ts", "aggregators"),
            dl("dexs/hashflow/index.ts"),
            dl("dexs/woofi/index.ts"),
            dl("aggregators/okx/index.ts", "aggregators"),
            dl("aggregators/enso/index.ts", "aggregators"),
            dl("aggregators/lifi/index.ts", "aggregators"),
            dl("aggregators/rango/index.ts", "aggregators"),
            dl("aggregators/rubic/index.ts", "aggregators"),
            dl("dexs/native/index.ts"),
        ),
        notes="Reference and quote-intel surface only unless routed through audited Executor lanes.",
    ),
)
