"""Compatibility package for the former solver-driver protocol namespace."""

from degenbot.protocol.models import (
    Allowance,
    Asset,
    Auction,
    BigIntStr,
    BuyTokenBalance,
    Call,
    CompetitionSolution,
    DriverError,
    DriverQuoteRequest,
    DriverQuoteResponse,
    Interaction,
    JitOrder,
    JitTradeOrder,
    Order,
    OrderClass,
    OrderKind,
    SellTokenBalance,
    SigningScheme,
    Solution,
    SolveRequest,
    SolveRequestBody,
    SolveResponse,
    TokenInfo,
    Trade,
)

__all__ = [
    "Allowance",
    "Asset",
    "Auction",
    "BigIntStr",
    "BuyTokenBalance",
    "Call",
    "CompetitionSolution",
    "DriverError",
    "DriverQuoteRequest",
    "DriverQuoteResponse",
    "Interaction",
    "JitOrder",
    "JitTradeOrder",
    "Order",
    "OrderClass",
    "OrderKind",
    "SellTokenBalance",
    "SigningScheme",
    "Solution",
    "SolveRequest",
    "SolveRequestBody",
    "SolveResponse",
    "TokenInfo",
    "Trade",
]
